# Generated by Django 5.1.6 on 2025-03-02 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_reviews_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='movie',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
