# Generated by Django 5.1.6 on 2025-03-02 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_reviews_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='review',
            field=models.TextField(default='None', max_length=999),
        ),
    ]
