services:
  db:
    image: postgres:16.8
    container_name: desafio-postgres-container
    restart: always
    environment:
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: strongermonkey
      POSTGRES_DB: filmreviewer_db
    ports:
      - "5433:5433"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    container_name: desafio-django-container
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://appuser:strongermonkey@db:5433/filmreviewer_db"
    ports:
      - "8000:8000"
    volumes:
      - .:/app

volumes:
  postgres_data:

